version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    container_name: water-jug-challenge-nestjs_api
    command: yarn start:dev
    ports:
      - 3000:3000
    networks:
      - base_service_network
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules

volumes:
  nodemodules:

networks:
  base_service_network:
    driver: bridge
