version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    container_name: base-service_api
    command: yarn dev:docker
    ports:
      - 3000:3000
    networks:
      - base_service_network
    env_file:
      - .env.docker
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules

volumes:
  nodemodules:

networks:
  base_service_network:
    driver: bridge
